services:
  lint:
    build:
      context: .
      dockerfile: Dockerfile.lint
    profiles: ["dev"]
    # Building this service runs all linters at build-time
  caddy:
    image: caddy:2.8
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file: .env
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
      - ADDR=${ADDR}
      - TLS_DIRECTIVE=${TLS_DIRECTIVE}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./web/dist:/srv:ro
    depends_on:
      - api
    networks:
      - loancalc

  api:
    build: ./api
    restart: unless-stopped
    volumes:
      - data:/data
    networks:
      - loancalc

  web:
    build: ./web
    restart: unless-stopped
    command: tail -f /dev/null
    networks:
      - loancalc

volumes:
  caddy_data:
  caddy_config:
  data:

networks:
  loancalc:
