services:
  caddy:
    image: caddy:2.8
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file: .env
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
      - ADDR=${ADDR}
      - TLS_DIRECTIVE=${TLS_DIRECTIVE}
      - API_UPSTREAM=api:8000
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./web/dist:/srv:ro
    depends_on:
      - api

  api:
    build: ./api
    restart: unless-stopped
    volumes:
      - data:/data

  web:
    build: ./web
    restart: unless-stopped
    command: tail -f /dev/null

volumes:
  caddy_data:
  caddy_config:
  data:
