services:
  edge:
    image: caddy:2.8
    container_name: loancalc-edge
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file: .env
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
      - APEX_HOST=${APEX_HOST}
      - WWW_HOST=${WWW_HOST}
      - TLS_DIRECTIVE=${TLS_DIRECTIVE}
    volumes:
      - ./Caddyfile.edge:/etc/caddy/Caddyfile
      - edge_caddy_data:/data
    networks:
      - edge-net

  caddy:
    image: caddy:2.8
    container_name: ${PROJECT_NAME}-caddy
    restart: unless-stopped
    networks:
      - edge-net
      - default
    environment:
      - API_UPSTREAM=api:8000
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./web/dist:/srv
    depends_on:
      - api

  api:
    build: ./api
    restart: unless-stopped
    networks:
      - default

  web:
    build: ./web
    restart: unless-stopped
    command: tail -f /dev/null
    networks:
      - default

  lint:
    build:
      context: .
      dockerfile: Dockerfile.lint
    image: loancalc/lint:latest
    profiles: ["dev"]

volumes:
  edge_caddy_data:
    external: true

networks:
  edge-net:
    external: true
  default:
