services:
  caddy:
    image: caddy:2.8
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file: .env
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./web/dist:/srv:ro
    depends_on:
      - api
    networks:
      - loancalc

  api:
    build: ./api
    restart: unless-stopped
    networks:
      - loancalc

volumes:
  caddy_data:
  caddy_config:

networks:
  loancalc:
