services:
  lint:
    build:
      context: .
      dockerfile: Dockerfile.lint
    image: loancalc/lint:latest
    # Building this service runs all linters at build-time
  caddy:
    image: caddy:2.8
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file: .env
    environment:
      - APEX_HOST=${APEX_HOST}
      - WWW_HOST=${WWW_HOST}
      - EMAIL=${EMAIL}
      - HSTS_LINE=${HSTS_LINE}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./web/dist:/srv:ro
    depends_on:
      - api
    networks:
      - loancalc

  api:
    build: ./api
    restart: unless-stopped
    environment:
      - PERSIST_DIR=/data
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    volumes:
      - leads_data:/data
    networks:
      - loancalc

  web:
    build: ./web
    restart: unless-stopped
    command: tail -f /dev/null
    networks:
      - loancalc

volumes:
  caddy_data:
  caddy_config:
  leads_data:

networks:
  loancalc:
