services:
  caddy:
    image: caddy:2.8
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file: .env
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - webdist:/srv:ro
    depends_on:
      - web
      - api
    networks:
      - loancalc

  web:
    build: ./web
    restart: unless-stopped
    command: tail -f /dev/null
    volumes:
      - webdist:/site:ro
    networks:
      - loancalc

  api:
    build: ./api
    restart: unless-stopped
    networks:
      - loancalc

volumes:
  caddy_data:
  caddy_config:
  webdist:

networks:
  loancalc:
